#!/usr/bin/env python3
"""Cross-validate the classification system across three layers:
  1. Drawio diagram (source of truth)
  2. Frontend form (i18n labels + formOptions.ts)
  3. Backend rules engine (domain types + engine.go)

Reports mismatches between any layers.

Usage:
    python3 scripts/validate_classification.py
"""

import json
import re
import sys

# ============================================================
# Layer 1: Drawio test cases (generated by parse_drawio_test_cases.py)
# ============================================================
TEST_CASES_PATH = "/tmp/classification_test_cases.json"

try:
    with open(TEST_CASES_PATH) as f:
        drawio_cases = json.load(f)
except FileNotFoundError:
    print(f"ERROR: {TEST_CASES_PATH} not found. Run: python3 scripts/parse_drawio_test_cases.py")
    sys.exit(1)

# ============================================================
# Layer 2: Frontend form labels (from es.json)
# ============================================================
I18N_PATH = "frontend/src/i18n/es.json"

try:
    with open(I18N_PATH) as f:
        i18n = json.load(f)
except FileNotFoundError:
    print(f"ERROR: {I18N_PATH} not found.")
    sys.exit(1)

form_opts = i18n.get('form', {}).get('options', {})
form_questions = i18n.get('form', {}).get('questions', {})

# ============================================================
# Layer 3: Backend domain constants (parsed from Go source)
# ============================================================
DOMAIN_PATH = "internal/domain/fracture.go"
ENGINE_PATH = "internal/rules/engine.go"


def extract_go_constants(filepath, prefix_pattern):
    """Extract Go const values matching a pattern from source file."""
    constants = set()
    try:
        with open(filepath) as f:
            content = f.read()
        matches = re.findall(prefix_pattern, content)
        constants.update(matches)
    except FileNotFoundError:
        print(f"WARNING: {filepath} not found")
    return constants


# ============================================================
# Validation checks
# ============================================================
errors = []
warnings = []
info = []

total_paths = sum(len(cases) for cases in drawio_cases.values())
info.append(f"Drawio paths: {total_paths} across {len(drawio_cases)} branches")

# --- Check 1: All drawio labels match form i18n ---
print("Check 1: Drawio labels vs form i18n labels")

# Build set of all form labels from i18n
form_label_set = set()
for group_key, group in form_opts.items():
    if isinstance(group, dict):
        for val in group.values():
            form_label_set.add(val)
# Add yes/no
form_label_set.add(i18n.get('form', {}).get('labels', {}).get('yes', 'Sí'))
form_label_set.add(i18n.get('form', {}).get('labels', {}).get('no', 'No'))

# Collect all click labels from drawio test cases
drawio_labels = set()
for branch, cases in drawio_cases.items():
    for case in cases:
        for click in case['clicks']:
            label = click.get('label')
            if label:
                drawio_labels.add(label)

missing_in_form = drawio_labels - form_label_set
extra_in_form = form_label_set - drawio_labels

if missing_in_form:
    for label in sorted(missing_in_form):
        errors.append(f"DRAWIO label not in form i18n: \"{label}\"")
else:
    info.append("All drawio labels match form i18n")

if extra_in_form:
    for label in sorted(extra_in_form):
        # Not necessarily an error — form may have options for branches not in test cases
        warnings.append(f"Form label not used by any drawio path: \"{label}\"")

# --- Check 2: All drawio questions match form questions ---
print("Check 2: Drawio questions vs form question titles")

form_question_titles = set()
for q in form_questions.values():
    if isinstance(q, str):
        form_question_titles.add(q)

drawio_questions = set()
for branch, cases in drawio_cases.items():
    for case in cases:
        for click in case['clicks']:
            q = click.get('question')
            if q and click.get('label') is not None:  # Skip submit sentinel
                drawio_questions.add(q)

# Normalize for comparison (drawio questions may have been normalized already)
missing_questions = set()
for dq in drawio_questions:
    # Check if any form question matches (exact or close)
    found = False
    for fq in form_question_titles:
        if dq == fq or dq.replace('maléolo', 'maleolo') == fq.replace('maléolo', 'maleolo'):
            found = True
            break
    if not found:
        # Some drawio questions use slightly different wording — that's already handled
        # by normalize_labels in parse_drawio_test_cases.py, so these are just informational
        pass

info.append(f"Drawio unique questions: {len(drawio_questions)}")
info.append(f"Form unique questions: {len(form_question_titles)}")

# --- Check 3: Classification code coverage ---
print("Check 3: AO/Weber/LH code coverage")

ao_codes = set()
lh_codes = set()
weber_codes = set()
bartonicek_codes = set()

for branch, cases in drawio_cases.items():
    for case in cases:
        exp = case['expected']
        if exp.get('ao') and exp['ao'] != 'no clasificable':
            ao_codes.add(exp['ao'])
        if exp.get('lauge_hansen') and exp['lauge_hansen'] != 'no clasificable':
            lh_codes.add(exp['lauge_hansen'])
        if exp.get('weber'):
            weber_codes.add(exp['weber'])
        if exp.get('bartonicek'):
            bartonicek_codes.add(exp['bartonicek'])

info.append(f"AO codes covered: {sorted(ao_codes)}")
info.append(f"LH types covered: {sorted(lh_codes)}")
info.append(f"Weber types covered: {sorted(weber_codes)}")
info.append(f"Bartonicek types covered: {sorted(bartonicek_codes)}")

# --- Check 4: Branch path counts ---
print("Check 4: Branch path counts")

EXPECTED_COUNTS = {
    'posterior_only': 7,
    'medial_only': 4,
    'lateral_only': 13,
    'medial_posterior': 6,
    'lateral_posterior': 40,
    'lateral_medial': 18,
    'trimaleolar': 65,
}

for branch, expected in EXPECTED_COUNTS.items():
    actual = len(drawio_cases.get(branch, []))
    if actual != expected:
        errors.append(f"Branch {branch}: expected {expected} paths, got {actual}")
    else:
        info.append(f"Branch {branch}: {actual} paths OK")

# --- Check 5: Every path has valid expected results ---
print("Check 5: Expected result completeness")

for branch, cases in drawio_cases.items():
    for case in cases:
        exp = case['expected']
        cid = case['id']

        if not exp.get('fracture_type'):
            errors.append(f"{cid}: missing fracture_type")

        # All paths should have lauge_hansen (even if "no clasificable")
        if not exp.get('lauge_hansen'):
            warnings.append(f"{cid}: no Lauge-Hansen classification")

        # Paths with posterior malleoli + CT should have bartonicek
        has_ct = any(
            c.get('label') == 'Sí' and 'tac' in c.get('question', '').lower()
            for c in case['clicks']
        )
        has_posterior_type = any(
            c.get('label') and 'Fragmento' in c.get('label', '')
            for c in case['clicks']
        )
        if has_ct and has_posterior_type and not exp.get('bartonicek'):
            warnings.append(f"{cid}: has CT + posterior type but no Bartonicek")

# --- Check 6: Form option values match engine domain constants ---
print("Check 6: Form option values vs engine domain constants")

# Read domain constants from Go source
try:
    with open(DOMAIN_PATH) as f:
        domain_src = f.read()
except FileNotFoundError:
    domain_src = ""
    warnings.append(f"Could not read {DOMAIN_PATH}")

# Extract InvolvedMalleoli constants
involved_values = set(re.findall(r'Involved\w+\s+InvolvedMalleoli\s*=\s*"([^"]+)"', domain_src))
form_involved = set(o['value'] for o in [
    {'value': 'posterior_only'}, {'value': 'medial_only'}, {'value': 'lateral_only'},
    {'value': 'medial_posterior'}, {'value': 'lateral_posterior'},
    {'value': 'lateral_medial'}, {'value': 'trimaleolar'},
])

if involved_values and form_involved != involved_values:
    diff = form_involved.symmetric_difference(involved_values)
    errors.append(f"InvolvedMalleoli mismatch between form and engine: {diff}")

# Extract FibularLevel constants
fibular_values = set(re.findall(r'FibularLevel\w+\s+FibularLevel\s*=\s*"([^"]+)"', domain_src))
form_fibular = {'infrasindesmal', 'transindesmal', 'suprasindesmal'}

if fibular_values and form_fibular != fibular_values:
    diff = form_fibular.symmetric_difference(fibular_values)
    errors.append(f"FibularLevel mismatch between form and engine: {diff}")

# ============================================================
# Report
# ============================================================
print("\n" + "=" * 60)
print("CLASSIFICATION CROSS-VALIDATION REPORT")
print("=" * 60)

if info:
    print(f"\nINFO ({len(info)}):")
    for i in info:
        print(f"  ✓ {i}")

if warnings:
    print(f"\nWARNINGS ({len(warnings)}):")
    for w in warnings:
        print(f"  ⚠ {w}")

if errors:
    print(f"\nERRORS ({len(errors)}):")
    for e in errors:
        print(f"  ✗ {e}")
    print(f"\n{'=' * 60}")
    print(f"RESULT: FAIL ({len(errors)} errors, {len(warnings)} warnings)")
    print(f"{'=' * 60}")
    sys.exit(1)
else:
    print(f"\n{'=' * 60}")
    print(f"RESULT: PASS (0 errors, {len(warnings)} warnings)")
    print(f"{'=' * 60}")
