---
config:
  layout: dagre
---
flowchart TB
    A{{"¿Tiene fractura del maléolo medial?"}} --> A1["Sí"] & A2["No"]
    B{{"¿Tiene fractura del maléolo lateral?"}} --> B1["Sí"] & B2["No"]
    A2 --> B
    B2 --> C["Presenta fractura aislada del maléolo posterior"]
    n3@{ label: "<span style=\"background-color:\">¿Cuál es el nivel de</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">fractura del peroné?</span>" } --> n4@{ label: "<span style=\"background-color:\">Transindesmal</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">(A nivel de sindesmosis)</span>" } & n5@{ label: "<span style=\"background-color:\">Infrasindesmal</span><br style=\"--tw-scale-x:\"><br>" } & n6@{ label: "<span style=\"background-color:\">Dudoso</span>" } & n7@{ label: "<span style=\"background-color:\">Suprasindesmal Alto</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">(&gt;6cm sobre sindesmosis)</span>" }
    n4 --> n8@{ label: "<span style=\"background-color:\">¿Cuál es la morfología</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">de la fractura del peroné?</span>" }
    n6 --> n8
    n8 --> n9@{ label: "<span style=\"background-color:\">Transversal</span>" } & n10["Oblicua (Baja medial / alta lateral )"] & n11@{ label: "<span style=\"background-color:\">Espiroidea (Baja anterior / alta posterior)</span>" }
    n9 --> n12@{ label: "<span style=\"color:\">¿Qué maléolos?</span>" }
    n10 --> n13["¿A qué nivel?"]
    n1{{"Morfología del maléolo medial"}} --> n15["Oblicua / vertical"] & n16["Transversal"] & n17["Dudosa"]
    n15 --> n18{{"¿Fractura transversa del maléolo peroneo?"}}
    n18 --> n19["Sí"] & n20["No"]
    n19 --> n12
    n20 --> n8
    n16 --> n8
    n17 --> n8
    n13 --> n22@{ label: "<span style=\"background-color:\">Infrasindesmal</span>" } & n21["Transindesmal"] & n23@{ label: "<span style=\"background-color:\">Suprasindesmal</span>" }
    n5 --> n28["¿Es transversa?"]
    n28 --> n30["No"] & n29["Sí"]
    n30 --> n8
    n29 --> n12
    A1 --> n31["¿Solo el maléolo medial?"]
    n31 --> n33["No"] & n32["Sí"]
    n32 --> n27(["Fractura unimaleolar del maléolo medial<br>AO-44-A1<br>Lauge-Hansen PER/PA"])
    n33 --> n34["¿Cuál más presenta?"]
    n34 --> n35["Medial + Posterior"] & n37["Medial + Lateral ± posterior"]
    n35 --> n36@{ label: "Fractura bimaleolar maléolo medial + posterior<br>AO-44-A2<br>Lauge-Hansen PA<br style=\"--tw-scale-x:\">" }
    n37 --> n1
    B1 --> n38{{"¿Presenta fractura aislada del maléolo lateral?"}}
    n38 --> n39["Sí"] & n40["No"]
    n39 --> n41{{"¿A qué nivel?"}}
    n41 --> n42@{ label: "<span style=\"background-color:\">Infrasindesmal</span><br style=\"--tw-scale-x:\"><br>" } & n43@{ label: "<span style=\"background-color:\">Transindesmal</span><br>" } & n44["Suprasindesmal"]
    n42 --> n45@{ label: "Weber A<br>AO-44-A1<br>Lauge-Hansen SA<span style=\"color:\"></span>" }
    n43 --> n46@{ label: "Weber B<br>AO-44-B1<br>Lauge-Hansen SER<span style=\"color:\"></span>" }
    n44 --> n48["¿De qué tipo?"]
    n48 --> n49["Diafisaria Simple"] & n50["Multifragmentaria"] & n51["Proximal"]
    n49 --> n52@{ label: "Weber C<br>AO-44-C1<br>Lauge-Hansen PER<span style=\"color:\"></span>" }
    n50 --> n53@{ label: "Weber C<br>AO-44-C2<br>Lauge-Hansen PER<span style=\"color:\"></span>" }
    n51 --> n54@{ label: "Weber C<br>AO-44-C3<br>Lauge-Hansen PER<span style=\"color:\"></span>" }
    n56@{ label: "<span style=\"background-color:\">Unifocal</span>" } --> n59@{ label: "<span style=\"color:\">Lauge-Hansen SA<br></span>Weber A<br>AO-44-A1<span style=\"color:\"></span>" }
    n57["Bifocal"] --> n60@{ label: "<span style=\"color:\">Lauge-Hansen SA<br></span>Weber A<br>AO-44-A2<span style=\"color:\"></span>" }
    n58["Maléolos lateral, medial y posterior"] --> n61@{ label: "<span style=\"color:\">Lauge-Hansen SA<br></span>Weber A<br>AO-44-A3<span style=\"color:\"></span>" }
    n12 --> n56 & n57 & n58
    n11 --> n62["¿Qué maléolos?"]
    n62 --> n63@{ label: "<span style=\"background-color:\">Maléolo lateral aislado</span>" } & n64["Maléolos lateral y medial"] & n65["Maléolos lateral, medial y posterior"]
    n63 --> n14@{ label: "<span style=\"color:\">Lauge-Hansen SER<br></span>Weber B<br>AO-44-B1<span style=\"color:\"></span>" }
    n64 --> n66@{ label: "<span style=\"color:\">Lauge-Hansen SER<br></span>Weber B<br>AO-44-B2<span style=\"color:\"></span>" }
    C --> n68{{"¿Qué tipo de fractura?"}}
    n68 --> n69["Tipo 1: fragmento extraincisural"] & n71["Tipo 2: fragmento posterolateral"] & n72["Tipo 3: fragmento posteromedial y posterolateral"] & n73["Tipo 4: gran fragmento triangular posterolateral"]
    n69 --> n74@{ label: "Bartonicek 1<br><span style=\"color:\"></span>" }
    n71 --> n76@{ label: "Bartonicek 2<br><span style=\"color:\"></span>" }
    n72 --> n75@{ label: "Bartonicek 3<br><span style=\"color:\"></span>" }
    n73 --> n77@{ label: "Bartonicek 4<br><span style=\"color:\"></span>" }
    n22 --> n78@{ label: "<span style=\"color:\">¿Qué maléolos?</span>" }
    n78 --> n79@{ label: "<span style=\"color:\">Lauge-Hansen PA<br>Weber A<br></span>AO-44-A3<span style=\"color:\"></span>" } & n80["Bifocal"] & n81["Maléolos lateral, medial y posterior"]
    n79 --> n24@{ label: "<span style=\"color:\">Lauge-Hansen PA<br>Weber A<br></span>AO-44-A1<span style=\"color:\"></span>" }
    n80 --> n82@{ label: "<span style=\"color:\">Lauge-Hansen PA<br>Weber A<br></span>AO-44-A2<span style=\"color:\"></span>" }
    n81 --> n145@{ label: "<span style=\"color:\">¿Qué tipo de fractura presenta el maléolo posterior?</span>" }
    n85["¿Qué maléolos?"] --> n86@{ label: "<span style=\"background-color:\">Maléolo lateral aislado</span>" } & n87["Maléolos lateral y medial"] & n88["Maléolos lateral, medial y posterior"]
    n21 --> n85
    n92["¿De qué tipo?"] --> n93["Multifragmentaria"] & n94["Diafisaria simple"] & n95["Proximal<br>"]
    n94 --> n96@{ label: "<span style=\"color:\">Lauge-Hansen PA<br>Weber C<br></span>AO-44-C1<span style=\"color:\"></span>" }
    n93 --> n97@{ label: "<span style=\"color:\">Lauge-Hansen PA<br>Weber C<br></span>AO-44-C2<span style=\"color:\"></span>" }
    n95 --> n98@{ label: "<span style=\"color:\">Lauge-Hansen PA<br>Weber C<br></span>AO-44-C3<span style=\"color:\"></span>" }
    n23 --> n92
    n100["¿De qué tipo?"] --> n101["Diafisaria simple"] & n102["Multifragmentaria"] & n103["Proximal"]
    n101 --> n104@{ label: "Weber C<br>AO-44-C1<br>Lauge-Hansen PER<span style=\"color:\"></span>" }
    n102 --> n105@{ label: "Weber C<br>AO-44-C2<br>Lauge-Hansen PER<span style=\"color:\"></span>" }
    n103 --> n106@{ label: "Weber C<br>AO-44-C3<br>Lauge-Hansen PER<span style=\"color:\"></span>" }
    n7 --> n100
    n40 --> n3
    n86 --> n25@{ label: "<span style=\"color:\">Lauge-Hansen PA<br>Weber B<br></span>AO-44-B1<span style=\"color:\"></span>" }
    n87 --> n89@{ label: "<span style=\"color:\">Lauge-Hansen PA<br>Weber B<br></span>AO-44-B2<span style=\"color:\"></span>" }
    n117{{"¿Qué tipo de fractura presenta el maléolo posterior?"}} --> n118["Tipo 1: fragmento extraincisural"] & n119["Tipo 2: fragmento posterolateral"] & n120["Tipo 3: fragmento posteromedial y posterolateral"] & n121["Tipo 4: gran fragmento triangular posterolateral"]
    n118 --> n122@{ label: "<span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\">Weber B<br style=\"--tw-scale-x:\"></span>AO-44-B3<br>Bartonicek 1<br><span style=\"color:\"></span>" }
    n119 --> n123@{ label: "<span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\">Weber B<br style=\"--tw-scale-x:\"></span>AO-44-B3<br>Bartonicek 2<br><span style=\"color:\"></span>" }
    n120 --> n124@{ label: "<span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\">Weber B<br style=\"--tw-scale-x:\"></span>AO-44-B3<br>Bartonicek 3<br><span style=\"color:\"></span>" }
    n121 --> n125@{ label: "<span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\">Weber B<br style=\"--tw-scale-x:\"></span>AO-44-B3<br>Bartonicek 4<br><span style=\"color:\"></span>" }
    n126{{"¿Qué tipo de fractura presenta el maléolo posterior?"}} --> n127["Tipo 1: fragmento extraincisural"] & n128["Tipo 2: fragmento posterolateral"] & n129["Tipo 3: fragmento posteromedial y posterolateral"] & n130["Tipo 4: gran fragmento triangular posterolateral"]
    n127 --> n131@{ label: "<span style=\"--tw-scale-x:\">Lauge-Hansen SER<br style=\"--tw-scale-x:\"></span>Weber B<br style=\"--tw-scale-x:\">AO-44-B3<br>Bartonicek 1<br><span style=\"color:\"></span>" }
    n128 --> n132@{ label: "<span style=\"--tw-scale-x:\">Lauge-Hansen SER<br style=\"--tw-scale-x:\"></span>Weber B<br style=\"--tw-scale-x:\">AO-44-B3<br>Bartonicek 2<br><span style=\"color:\"></span>" }
    n129 --> n133@{ label: "<span style=\"--tw-scale-x:\">Lauge-Hansen SER<br style=\"--tw-scale-x:\"></span>Weber B<br style=\"--tw-scale-x:\">AO-44-B3<br>Bartonicek 3<br><span style=\"color:\"></span>" }
    n130 --> n134@{ label: "<span style=\"--tw-scale-x:\">Lauge-Hansen SER<br style=\"--tw-scale-x:\"></span>Weber B<br style=\"--tw-scale-x:\">AO-44-B3<br>Bartonicek 4<br><span style=\"color:\"></span>" }
    n65 --> n126
    n88 --> n117
    n145 --> n146@{ label: "<span style=\"color:\">Tipo 1: fragmento extraincisural</span>" } & n147@{ label: "<span style=\"color:\">Tipo 2: fragmento posterolateral</span>" } & n148@{ label: "<span style=\"color:\">Tipo 3: fragmento posteromedial y posterolateral</span>" } & n149@{ label: "<span style=\"color:\">Tipo 4: gran fragmento triangular posterolateral</span>" }
    n146 --> n150@{ label: "<span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\">Weber A<br style=\"--tw-scale-x:\"></span><span style=\"color:\">AO-44-A2<br></span><span style=\"color:\">Bartonicek 1</span><span style=\"color:\"></span>" }
    n147 --> n151@{ label: "<span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\">Weber A<br style=\"--tw-scale-x:\"></span><span style=\"color:\">AO-44-A2<br></span><span style=\"color:\">Bartonicek 2</span><span style=\"color:\"></span>" }
    n148 --> n152@{ label: "<span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\">Weber A<br style=\"--tw-scale-x:\"></span><span style=\"color:\">AO-44-A2<br></span><span style=\"color:\">Bartonicek 3</span><span style=\"color:\"></span>" }
    n149 --> n153@{ label: "<span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\">Weber A<br style=\"--tw-scale-x:\"></span><span style=\"color:\">AO-44-A2<br></span><span style=\"color:\">Bartonicek 4</span><span style=\"color:\"></span>" }

    C@{ shape: diam}
    n3@{ shape: hexagon}
    n4@{ shape: rect}
    n5@{ shape: rect}
    n6@{ shape: rect}
    n7@{ shape: rect}
    n8@{ shape: hexagon}
    n9@{ shape: rect}
    n10@{ shape: rect}
    n11@{ shape: rect}
    n12@{ shape: hex}
    n13@{ shape: hex}
    n15@{ shape: rect}
    n16@{ shape: rect}
    n17@{ shape: rect}
    n19@{ shape: rect}
    n20@{ shape: rect}
    n22@{ shape: rect}
    n21@{ shape: rect}
    n23@{ shape: rect}
    n28@{ shape: hex}
    n30@{ shape: rect}
    n29@{ shape: rect}
    n31@{ shape: hex}
    n33@{ shape: rect}
    n32@{ shape: rect}
    n34@{ shape: hex}
    n35@{ shape: rect}
    n37@{ shape: rect}
    n36@{ shape: stadium}
    n39@{ shape: rect}
    n40@{ shape: rect}
    n42@{ shape: rect}
    n43@{ shape: rect}
    n44@{ shape: rect}
    n45@{ shape: stadium}
    n46@{ shape: stadium}
    n48@{ shape: hex}
    n49@{ shape: rect}
    n50@{ shape: rect}
    n51@{ shape: rect}
    n52@{ shape: stadium}
    n53@{ shape: stadium}
    n54@{ shape: stadium}
    n56@{ shape: rect}
    n59@{ shape: stadium}
    n57@{ shape: rect}
    n60@{ shape: stadium}
    n58@{ shape: rect}
    n61@{ shape: stadium}
    n62@{ shape: hex}
    n63@{ shape: rect}
    n64@{ shape: rect}
    n65@{ shape: rect}
    n14@{ shape: stadium}
    n66@{ shape: stadium}
    n69@{ shape: rect}
    n71@{ shape: rect}
    n72@{ shape: rect}
    n73@{ shape: rect}
    n74@{ shape: stadium}
    n76@{ shape: stadium}
    n75@{ shape: stadium}
    n77@{ shape: stadium}
    n78@{ shape: hex}
    n79@{ shape: rect}
    n80@{ shape: rect}
    n81@{ shape: rect}
    n24@{ shape: stadium}
    n82@{ shape: stadium}
    n145@{ shape: hex}
    n85@{ shape: hex}
    n86@{ shape: rect}
    n87@{ shape: rect}
    n88@{ shape: rect}
    n92@{ shape: hex}
    n93@{ shape: rect}
    n94@{ shape: rect}
    n95@{ shape: rect}
    n96@{ shape: stadium}
    n97@{ shape: stadium}
    n98@{ shape: stadium}
    n100@{ shape: hex}
    n101@{ shape: rect}
    n102@{ shape: rect}
    n103@{ shape: rect}
    n104@{ shape: stadium}
    n105@{ shape: stadium}
    n106@{ shape: stadium}
    n25@{ shape: stadium}
    n89@{ shape: stadium}
    n118@{ shape: rect}
    n119@{ shape: rect}
    n120@{ shape: rect}
    n121@{ shape: rect}
    n122@{ shape: stadium}
    n123@{ shape: stadium}
    n124@{ shape: stadium}
    n125@{ shape: stadium}
    n127@{ shape: rect}
    n128@{ shape: rect}
    n129@{ shape: rect}
    n130@{ shape: rect}
    n131@{ shape: stadium}
    n132@{ shape: stadium}
    n133@{ shape: stadium}
    n134@{ shape: stadium}
    n146@{ shape: rect}
    n147@{ shape: rect}
    n148@{ shape: rect}
    n149@{ shape: rect}
    n150@{ shape: stadium}
    n151@{ shape: stadium}
    n152@{ shape: stadium}
    n153@{ shape: stadium}
     A:::Aqua
     A1:::Peach
     A2:::Peach
     B:::Aqua
     B1:::Peach
     B2:::Peach
     C:::Sky
     n3:::Aqua
     n4:::Peach
     n5:::Peach
     n6:::Peach
     n7:::Peach
     n8:::Aqua
     n9:::Peach
     n10:::Peach
     n11:::Peach
     n12:::Aqua
     n13:::Aqua
     n1:::Aqua
     n15:::Peach
     n16:::Peach
     n17:::Peach
     n18:::Aqua
     n19:::Peach
     n20:::Peach
     n22:::Peach
     n21:::Peach
     n23:::Peach
     n28:::Aqua
     n30:::Peach
     n29:::Peach
     n31:::Aqua
     n33:::Peach
     n32:::Peach
     n27:::Rose
     n34:::Aqua
     n35:::Peach
     n37:::Peach
     n36:::Rose
     n38:::Aqua
     n39:::Peach
     n40:::Peach
     n41:::Aqua
     n42:::Peach
     n43:::Peach
     n44:::Peach
     n45:::Rose
     n46:::Rose
     n48:::Aqua
     n49:::Peach
     n50:::Peach
     n51:::Peach
     n52:::Rose
     n53:::Rose
     n54:::Rose
     n56:::Peach
     n59:::Rose
     n57:::Peach
     n60:::Rose
     n58:::Peach
     n61:::Rose
     n62:::Aqua
     n63:::Peach
     n64:::Peach
     n65:::Peach
     n14:::Rose
     n66:::Rose
     n68:::Aqua
     n69:::Peach
     n71:::Peach
     n72:::Peach
     n73:::Peach
     n74:::Rose
     n76:::Rose
     n75:::Rose
     n77:::Rose
     n78:::Aqua
     n79:::Peach
     n80:::Peach
     n81:::Peach
     n24:::Rose
     n82:::Rose
     n145:::Aqua
     n85:::Aqua
     n86:::Peach
     n87:::Peach
     n88:::Peach
     n92:::Aqua
     n93:::Peach
     n94:::Peach
     n95:::Peach
     n96:::Rose
     n97:::Rose
     n98:::Rose
     n100:::Aqua
     n101:::Peach
     n102:::Peach
     n103:::Peach
     n104:::Rose
     n105:::Rose
     n106:::Rose
     n25:::Rose
     n89:::Rose
     n117:::Aqua
     n118:::Peach
     n119:::Peach
     n120:::Peach
     n121:::Peach
     n122:::Rose
     n123:::Rose
     n124:::Rose
     n125:::Rose
     n126:::Aqua
     n127:::Peach
     n128:::Peach
     n129:::Peach
     n130:::Peach
     n131:::Rose
     n132:::Rose
     n133:::Rose
     n134:::Rose
     n146:::Peach
     n147:::Peach
     n148:::Peach
     n149:::Peach
     n150:::Rose
     n151:::Rose
     n152:::Rose
     n153:::Rose
    classDef Sky stroke-width:1px, stroke-dasharray:none, stroke:#374D7C, fill:#E2EBFF, color:#374D7C
    classDef Peach stroke-width:1px, stroke-dasharray:none, stroke:#FBB35A, fill:#FFEFDB, color:#8F632D
    classDef Rose stroke-width:1px, stroke-dasharray:none, stroke:#FF5978, fill:#FFDFE5, color:#8E2236
    classDef Aqua stroke-width:1px, stroke-dasharray:none, stroke:#46EDC8, fill:#DEFFF8, color:#378E7A