---
config:
  theme: redux
  layout: dagre
---
flowchart TB
    A(["Danis-Weber AO/OTA Flow"]) --> B{"Which malleoli are fractured?"}
    B --> C["Posterior malleolus"] & D["Medial malleolus"] & n1["Lateral malleolus"] & n2["Medial and posterior malleoli"] & n3["Lateral and posterior malleoli"] & n4["Lateral and medial malleoli"] & n5["Medial, lateral and posterior malleoli"]
    C --> n379["What is the involvement?"]
    n6["What is the posterior malleolus fracture type?"] --> n7@{ label: "<span style=\"color:\">Extraincisural fragment</span>" } & n8@{ label: "<span style=\"color:\">Posterolateral fragment</span>" } & n9@{ label: "<span style=\"color:\">Posteromedial and posterolateral fragment</span>" } & n10@{ label: "<span style=\"color:\">Large posterolateral triangular fragment</span>" }
    n7 --> n11@{ label: "<span style=\"color:\">Unimalleolar fracture posterior malleolus</span><span style=\"color:\"><br>AO Unclassifiable<br></span>Lauge-Hansen PA<br style=\"--tw-scale-x:\"><span style=\"color:\">Bartonicek 1</span>" }
    n8 --> n12@{ label: "<span style=\"--tw-scale-x:\"><span style=\"color:\">Unimalleolar fracture posterior malleolus</span><br></span><span style=\"--tw-scale-x:\">AO Unclassifiable<br style=\"--tw-scale-x:\"></span>Lauge-Hansen PA<span style=\"color:\"><br>Bartonicek 2</span>" }
    n9 --> n13@{ label: "<span style=\"--tw-scale-x:\"><span style=\"color:\">Unimalleolar fracture posterior malleolus</span><br></span><span style=\"--tw-scale-x:\">AO Unclassifiable<br style=\"--tw-scale-x:\"></span>Lauge-Hansen PA<span style=\"color:\"><br>Bartonicek 3</span>" }
    n10 --> n14@{ label: "<span style=\"--tw-scale-x:\"><span style=\"color:\">Unimalleolar fracture posterior malleolus</span><br></span><span style=\"--tw-scale-x:\">AO Unclassifiable<br style=\"--tw-scale-x:\"></span>Lauge-Hansen PA<br><span style=\"color:\">Bartonicek 4</span>" }
    D --> n388["Is there significant articular involvement with metaphyseal extension?"]
    n15["What is the morphology?"] --> n16["Vertical"] & n17["Transverse/oblique"]
    n16 --> n18@{ label: "<span style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Unimalleolar fracture medial malleolus</span><br style=\"--tw-scale-x:\">AO 44 A2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen SA</span><span style=\"--tw-scale-x:\"><br></span>" }
    n17 --> n19@{ label: "<span style=\"--tw-scale-x:\">Unimalleolar fracture medial malleolus<br>AO 44 A2<br>Lauge-Hansen unclassifiable (could be PA/SER/PER)<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\"><br></span>" }
    n1 --> n20["At what level is the fracture?"]
    n20 --> n21@{ label: "<span style=\"--tw-scale-x:\">Infrasyndesmotic</span><br style=\"--tw-scale-x:\">" } & n22@{ label: "<span style=\"color:\">Transsyndesmotic</span>" } & n23@{ label: "<span style=\"color:\">Suprasyndesmotic</span>" }
    n21 --> n27@{ label: "<span style=\"--tw-scale-x:\">Unimalleolar fracture lateral malleolus</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 A1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen SA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber A</span><br>" }
    n22 --> n29["What is the fracture morphology?"]
    n29 --> n30["Spiral (Low anterior, high posterior)"] & n31["Transverse/Oblique(Low medial, high lateral)/Comminuted"]
    n30 --> n32@{ label: "<span style=\"--tw-scale-x:\">Unimalleolar fracture lateral malleolus</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B (subtype unclassifiable. B1/B2)<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen SER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B</span>" }
    n31 --> n33@{ label: "<span style=\"--tw-scale-x:\">Unimalleolar fracture lateral malleolus</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B (subtype unclassifiable B1/B2)<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B</span>" }
    n23 --> n34@{ label: "<span style=\"color:\">What type?</span>" }
    n34 --> n35@{ label: "<span style=\"color:\">Simple diaphyseal</span>" } & n36@{ label: "<span style=\"color:\">Multifragmentary</span>" } & n37@{ label: "<span style=\"color:\">Proximal (proximal 1/3 of fibula)</span>" }
    n35 --> n286["What is the main fibula trace pattern?"]
    n36 --> n290["What is the main fibula trace pattern?"]
    n37 --> n41@{ label: "<span style=\"--tw-scale-x:\">Unimalleolar fracture lateral malleolus</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\"></span>AO-44-C3<br style=\"--tw-scale-x:\">Lauge-Hansen PER<span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">Weber C</span>" }
    n2 --> n264["Is a CT scan available?"]
    n3 --> n43["At what level is the fibula fracture?"]
    n43 --> n44["Infrasyndesmotic"] & n45["Transsyndesmotic"] & n46["Suprasyndesmotic"]
    n44 --> n400["Is a CT scan available?"]
    n45 --> n48["What is the fracture morphology?"]
    n46 --> n49["What type?"]
    n48 --> n52["Spiral (Low anterior, high posterior)"] & n53["Transverse/Oblique(Low medial, high lateral)/Comminuted"]
    n49 --> n54["Simple diaphyseal"] & n55["Multifragmentary"] & n56["Proximal (proximal 1/3 of fibula)"]
    n67["What is the posterior malleolus fracture type?"] --> n68@{ label: "<span style=\"color:\">Extraincisural fragment</span>" } & n69@{ label: "<span style=\"color:\">Posterolateral fragment</span>" } & n70@{ label: "<span style=\"color:\">Posteromedial and posterolateral fragment</span>" } & n71@{ label: "<span style=\"color:\">Large posterolateral triangular fragment</span>" }
    n68 --> n72@{ label: "<span style=\"color:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"color:\"><br>AO 44 B3<br></span><span style=\"color:\">Lauge-Hansen SER<br></span><span style=\"color:\">Weber B</span><br style=\"--tw-scale-x:\"><span style=\"color:\">Bartonicek 1</span>" }
    n69 --> n73@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen SER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 2</span>" }
    n70 --> n74@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen SER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 3</span>" }
    n71 --> n75@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen SER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 4</span>" }
    n76["What is the posterior malleolus fracture type?"] --> n77@{ label: "<span style=\"color:\">Extraincisural fragment</span>" } & n78@{ label: "<span style=\"color:\">Posterolateral fragment</span>" } & n79@{ label: "<span style=\"color:\">Posteromedial and posterolateral fragment</span>" } & n80@{ label: "<span style=\"color:\">Large posterolateral triangular fragment</span>" }
    n77 --> n81@{ label: "<span style=\"color:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"color:\"><br>AO 44 B3<br></span><span style=\"color:\">Lauge-Hansen PA<br></span><span style=\"color:\">Weber B</span><br style=\"--tw-scale-x:\"><span style=\"color:\">Bartonicek 1</span>" }
    n78 --> n82@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 2</span>" }
    n79 --> n83@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 3</span>" }
    n80 --> n84@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 4</span>" }
    n52 --> n223["Is a CT scan available?"]
    n53 --> n227["Is a CT scan available?"]
    n85["What is the posterior malleolus fracture type?"] --> n86@{ label: "<span style=\"color:\">Extraincisural fragment</span>" } & n87@{ label: "<span style=\"color:\">Posterolateral fragment</span>" } & n88@{ label: "<span style=\"color:\">Posteromedial and posterolateral fragment</span>" } & n89@{ label: "<span style=\"color:\">Large posterolateral triangular fragment</span>" }
    n86 --> n90@{ label: "<span style=\"color:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"color:\"><br>AO 44 C1<br></span><span style=\"color:\">Lauge-Hansen PER<br></span><span style=\"color:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"color:\">Bartonicek 1</span>" }
    n87 --> n91@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 2</span>" }
    n88 --> n92@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 3</span>" }
    n89 --> n93@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 4</span>" }
    n94["What is the posterior malleolus fracture type?"] --> n95@{ label: "<span style=\"color:\">Extraincisural fragment</span>" } & n96@{ label: "<span style=\"color:\">Posterolateral fragment</span>" } & n97@{ label: "<span style=\"color:\">Posteromedial and posterolateral fragment</span>" } & n98@{ label: "<span style=\"color:\">Large posterolateral triangular fragment</span>" }
    n95 --> n99@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 1</span>" }
    n96 --> n100@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 2</span>" }
    n97 --> n101@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 3</span>" }
    n98 --> n102@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 4</span>" }
    n103["What is the posterior malleolus fracture type?"] --> n104@{ label: "<span style=\"color:\">Extraincisural fragment</span>" } & n105@{ label: "<span style=\"color:\">Posterolateral fragment</span>" } & n106@{ label: "<span style=\"color:\">Posteromedial and posterolateral fragment</span>" } & n107@{ label: "<span style=\"color:\">Large posterolateral triangular fragment</span>" }
    n104 --> n108@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 1</span>" }
    n105 --> n109@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 2</span>" }
    n106 --> n110@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 3</span>" }
    n107 --> n111@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 4</span>" }
    n54 --> n307["What is the fibula trace pattern?"]
    n55 --> n310["What is the main fibula trace pattern?"]
    n56 --> n237["Is a CT scan available?"]
    n4 --> n112["What is the medial malleolus fracture morphology?"]
    n112 --> n113["Vertical"] & n114["Transverse/oblique"]
    n113 --> n115["Is the fibula fracture infrasyndesmotic and transverse?"]
    n115 --> n116["Yes"] & n117["No"]
    n116 --> n118@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and medial malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 A2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen SA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber A</span><br>" }
    n114 --> n119["At what level is the fibula fracture?"]
    n117 --> n119
    n119 --> n120["High (Suprasyndesmotic)"] & n121["Low (Transsyndesmotic / Infrasyndesmotic)"]
    n120 --> n122["What type?"]
    n122 --> n123["Simple diaphyseal"] & n124["Multifragmentary"] & n125["Proximal (proximal 1/3 of fibula)"]
    n123 --> n336["What is the fibula trace pattern?"]
    n124 --> n340["What is the main fibula trace pattern?"]
    n125 --> n128@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and medial malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span>" }
    n121 --> n129["What is the fibula fracture morphology?"]
    n129 --> n130["Transverse"] & n131["Oblique(Low medial, high lateral)/Comminuted"] & n132["Spiral (Low anterior, high posterior)"]
    n130 --> n133["At what level is the fibula fracture?"]
    n133 --> n134["Infrasyndesmotic"] & n135["Transsyndesmotic"]
    n134 --> n136@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and medial malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 A2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen SA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber A</span>" }
    n135 --> n138@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and medial malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B</span>" }
    n131 --> n139@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and medial malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B</span>" }
    n132 --> n140@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and medial malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen SER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B</span>" }
    n5 --> n141["At what level is the fibula fracture?"]
    n141 --> n143["High (Suprasyndesmotic)"] & n152["Low (Transsyndesmotic / Infrasyndesmotic)"]
    n145["What type?"] --> n146["Simple diaphyseal"] & n147["Multifragmentary"] & n148["Proximal (proximal 1/3 of fibula)"]
    n146 --> n345["What is the fibula trace pattern?"]
    n147 --> n363["What is the main fibula trace pattern?"]
    n148 --> n249["Is a CT scan available?"]
    n143 --> n145
    n152 --> n153["What is the fibula fracture morphology?"]
    n153 --> n154["Transverse"] & n155["Oblique(Low medial, high lateral)/Comminuted"] & n156["Spiral (Low anterior, high posterior)"]
    n154 --> n157["At what level is the fibula fracture?"]
    n157 --> n158["Infrasyndesmotic"] & n159["Transsyndesmotic"]
    n158 --> n160@{ label: "<span style=\"--tw-scale-x:\">Not possible, exceptional mechanism</span>" }
    n159 --> n253["Is a CT scan available?"]
    n156 --> n260["Is a CT scan available?"]
    n164["What is the posterior malleolus fracture type?"] --> n165["Extraincisural fragment"] & n166["Posterolateral fragment"] & n167["Posteromedial and posterolateral fragment"] & n168["Large posterolateral triangular fragment"]
    n165 --> n169@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br>Bartonicek 1</span>" }
    n166 --> n170@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br style=\"--tw-scale-x:\">Bartonicek 2</span>" }
    n167 --> n171@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br style=\"--tw-scale-x:\">Bartonicek 3</span>" }
    n168 --> n172@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br style=\"--tw-scale-x:\">Bartonicek 4</span>" }
    n173["What is the posterior malleolus fracture type?"] --> n174["Extraincisural fragment"] & n175["Posterolateral fragment"] & n176["Posteromedial and posterolateral fragment"] & n177["Large posterolateral triangular fragment"]
    n174 --> n178@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br>Bartonicek 1</span>" }
    n175 --> n179@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br>Bartonicek 2</span>" }
    n176 --> n180@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br>Bartonicek 3</span>" }
    n177 --> n181@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br>Bartonicek 4</span>" }
    n182["What is the posterior malleolus fracture type?"] --> n183["Extraincisural fragment"] & n184["Posterolateral fragment"] & n185["Posteromedial and posterolateral fragment"] & n186["Large posterolateral triangular fragment"]
    n183 --> n187@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br>Bartonicek 1</span>" }
    n184 --> n188@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br>Bartonicek 2</span>" }
    n185 --> n189@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br>Bartonicek 3</span>" }
    n186 --> n190@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br>Bartonicek 4</span>" }
    n191["What is the posterior malleolus fracture type?"] --> n192["Extraincisural fragment"] & n193["Posterolateral fragment"] & n194["Posteromedial and posterolateral fragment"] & n195["Large posterolateral triangular fragment"]
    n192 --> n196@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B<br>Bartonicek 1</span>" }
    n193 --> n197@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B<br>Bartonicek 2</span>" }
    n194 --> n198@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B<br>Bartonicek 3</span>" }
    n195 --> n199@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B<br>Bartonicek 4</span>" }
    n201["What is the posterior malleolus fracture type?"] --> n206["Extraincisural fragment"] & n207["Posterolateral fragment"] & n208["Posteromedial and posterolateral fragment"] & n209["Large posterolateral triangular fragment"]
    n206 --> n214@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen SER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B<br>Bartonicek 1</span>" }
    n207 --> n215@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen SER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B<br>Bartonicek 2</span>" }
    n208 --> n216@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen SER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B<br>Bartonicek 3</span>" }
    n209 --> n217@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen SER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B<br>Bartonicek 4</span>" }
    n218["Is a CT scan available?"] --> n219["Yes"] & n387["No"]
    n219 --> n6
    n223 --> n224["Yes"] & n225["No"]
    n225 --> n226@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen SER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B</span><br style=\"--tw-scale-x:\">" }
    n224 --> n67
    n227 --> n228["Yes"] & n344["No"]
    n228 --> n76
    n230["Is a CT scan available?"] --> n231["Yes"] & n285["No"]
    n231 --> n85
    n233["Is a CT scan available?"] --> n234["Yes"] & n235["No"]
    n234 --> n94
    n235 --> n236@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span>" }
    n237 --> n238["Yes"] & n239["No"]
    n238 --> n103
    n239 --> n240@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br>" }
    n241["Is a CT scan available?"] --> n242["Yes"] & n243["No"]
    n242 --> n164
    n243 --> n244@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br></span><span style=\"--tw-scale-x:\">Weber C</span>" }
    n245["Is a CT scan available?"] --> n246["Yes"] & n247["No"]
    n246 --> n173
    n247 --> n248@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span>" }
    n249 --> n250["Yes"] & n251["No"]
    n250 --> n182
    n251 --> n252@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br></span>" }
    n253 --> n254["Yes"] & n255@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B</span>" }
    n254 --> n191
    n260 --> n261["Yes"] & n262["No"]
    n261 --> n201
    n262 --> n263@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen SER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B<br></span>" }
    n264 --> n265["Yes"] & n266["No"]
    n265 --> n267["What is the posterior malleolus fracture type?"]
    n267 --> n268["Extraincisural postero-medial fragment"] & n269["Posterior extraincisural fragment"] & n270["Posterolateral fragment"] & n271["Posteromedial and posterolateral fragment"] & n398["Large posterolateral triangular fragment"]
    n266 --> n272@{ label: "Bimalleolar fracture (Medial + Posterior)<br style=\"--tw-scale-x:\">AO unclassifiable<br style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\">" }
    n285 --> n232@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span>" }
    n286 --> n287["Parasyndesmotic (&lt;6cm from articular surface) short oblique/transverse trace"] & n288["Parasyndesmotic long oblique/spiral trace (&lt;6cm from articular surface)"] & n396["Suprasyndesmotic (&gt;6cm from articular surface)"]
    n288 --> n39@{ label: "<br><span style=\"--tw-scale-x:\">Unimalleolar fracture lateral malleolus</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\"></span>AO-44-C1<br>Lauge-Hansen PER<span style=\"color:\"><br>Weber C</span><br>" }
    n287 --> n289@{ label: "<span style=\"--tw-scale-x:\">Unimalleolar fracture lateral malleolus</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\"></span>AO-44-C1<br style=\"--tw-scale-x:\">Lauge-Hansen PA<span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">Weber C</span>" }
    n290 --> n291["Parasyndesmotic (&lt;6cm from articular surface) short oblique/transverse/comminuted trace"] & n292["Parasyndesmotic (&lt;6cm from articular surface) long oblique/spiral trace"] & n397["Suprasyndesmotic (&gt;6cm from articular surface)"]
    n292 --> n40@{ label: "<span style=\"--tw-scale-x:\">Unimalleolar fracture lateral malleolus</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\"></span>AO-44-C2<br style=\"--tw-scale-x:\">Lauge-Hansen PER<span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">Weber C</span>" }
    n291 --> n293@{ label: "<span style=\"--tw-scale-x:\">Unimalleolar fracture lateral malleolus</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\"></span>AO-44-C2<br style=\"--tw-scale-x:\">Lauge-Hansen PA<span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">Weber C</span>" }
    n294["What is the posterior malleolus fracture type?"] --> n295@{ label: "<span style=\"color:\">Extraincisural fragment</span>" } & n296@{ label: "<span style=\"color:\">Posterolateral fragment</span>" } & n297@{ label: "<span style=\"color:\">Posteromedial and posterolateral fragment</span>" } & n298@{ label: "<span style=\"color:\">Large posterolateral triangular fragment</span>" }
    n295 --> n299@{ label: "<span style=\"color:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"color:\"><br>AO 44 C1<br></span><span style=\"color:\">Lauge-Hansen PA<br></span><span style=\"color:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"color:\">Bartonicek 1</span>" }
    n296 --> n300@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 2</span>" }
    n297 --> n301@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br></span><span style=\"--tw-scale-x:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 3</span>" }
    n298 --> n302@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 4</span>" }
    n303["Is a CT scan available?"] --> n304["Yes"] & n305["No"]
    n304 --> n294
    n305 --> n306@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span>" }
    n307 --> n308["Parasyndesmotic (&lt;6cm from articular surface) short oblique/transverse trace"] & n309["Parasyndesmotic (&lt;6cm from articular surface) long oblique/spiral trace"] & n416["Suprasyndesmotic (&gt;6cm from articular surface)"]
    n309 --> n230
    n308 --> n303
    n310 --> n311["Parasyndesmotic (&lt;6cm from articular surface) short oblique/transverse/comminuted trace"] & n312["Parasyndesmotic (&lt;6cm from articular surface) long oblique/spiral trace"] & n417["Suprasyndesmotic (&gt;6cm from articular surface)"]
    n312 --> n233
    n311 --> n313["Is a CT scan available?"]
    n313 --> n314["Yes"] & n315["No"]
    n315 --> n316@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span>" }
    n314 --> n325["What is the posterior malleolus fracture type?"]
    n325 --> n326["Extraincisural fragment"] & n329["Posterolateral fragment"] & n330["Posteromedial and posterolateral fragment"] & n331["Large posterolateral triangular fragment"]
    n326 --> n332@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 1</span>" }
    n329 --> n333@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 2</span>" }
    n330 --> n334@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 3</span>" }
    n331 --> n335@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Bartonicek 4</span>" }
    n336 --> n337["Parasyndesmotic (&lt;6cm from articular surface) short oblique/transverse trace"] & n338["Parasyndesmotic (&lt;6cm from articular surface) long oblique/spiral trace"] & n420["Suprasyndesmotic (&gt;6cm from articular surface)"]
    n338 --> n126@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and medial malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span><br>" }
    n337 --> n339@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and medial malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span>" }
    n340 --> n341["Parasyndesmotic (&lt;6cm from articular surface) short oblique/transverse/comminuted trace"] & n342["Parasyndesmotic (&lt;6cm from articular surface) long oblique/spiral trace"] & n421["Suprasyndesmotic (&gt;6cm from articular surface)"]
    n342 --> n127@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and medial malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PER<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span>" }
    n341 --> n343@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and medial malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span>" }
    n344 --> n229@{ label: "<span style=\"--tw-scale-x:\">Bimalleolar fracture (lateral and posterior malleolus)</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber B</span>" }
    n345 --> n346["Parasyndesmotic (&lt;6cm from articular surface) short oblique/transverse trace"] & n347["Parasyndesmotic (&lt;6cm from articular surface) long oblique/spiral trace"] & n418["Suprasyndesmotic (&gt;6cm from articular surface)"]
    n347 --> n241
    n346 --> n348["Is a CT scan available?"]
    n348 --> n349["Yes"] & n350["No"]
    n349 --> n351["What is the posterior malleolus fracture type?"]
    n350 --> n352@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span>" }
    n351 --> n353["Extraincisural fragment"] & n354["Posterolateral fragment"] & n355["Posteromedial and posterolateral fragment"] & n356["Large posterolateral triangular fragment"]
    n353 --> n357@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br style=\"--tw-scale-x:\">Bartonicek 1</span>" }
    n354 --> n358@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br style=\"--tw-scale-x:\">Bartonicek 2</span>" }
    n355 --> n359@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br></span><span style=\"--tw-scale-x:\">Weber C<br style=\"--tw-scale-x:\">Bartonicek 3</span>" }
    n356 --> n362@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C1<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br style=\"--tw-scale-x:\">Bartonicek 4</span>" }
    n363 --> n364["Parasyndesmotic (&lt;6cm from articular surface) short oblique/transverse/comminuted trace"] & n365["Parasyndesmotic (&lt;6cm from articular surface) long oblique/spiral trace"] & n419["Suprasyndesmotic (&gt;6cm from articular surface)"]
    n365 --> n245
    n364 --> n366["Is a CT scan available?"]
    n366 --> n367["Yes"] & n368["No"]
    n368 --> n369@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C</span>" }
    n367 --> n370["What is the posterior malleolus fracture type?"]
    n370 --> n371["Extraincisural fragment"] & n372["Posterolateral fragment"] & n373["Posteromedial and posterolateral fragment"] & n374["Large posterolateral triangular fragment"]
    n371 --> n375@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br style=\"--tw-scale-x:\">Bartonicek 1</span>" }
    n372 --> n376@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br style=\"--tw-scale-x:\">Bartonicek 2</span>" }
    n373 --> n377@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br style=\"--tw-scale-x:\">Bartonicek 3</span>" }
    n374 --> n378@{ label: "<span style=\"--tw-scale-x:\">Trimalleolar fracture</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\">AO 44 C2<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Weber C<br style=\"--tw-scale-x:\">Bartonicek 4</span>" }
    n155 --> n253
    n379 --> n380["&gt;1/3 articular surface with metaphyseal extension"] & n381["&lt;1/3 articular surface without metaphyseal extension"]
    n380 --> n382["Is there articular depression?"]
    n381 --> n218
    n382 --> n383["No"] & n384["Yes"]
    n383 --> n385["Distal tibia fracture<br>AO 43 B1"]
    n384 --> n386@{ label: "Distal tibia fracture<br style=\"--tw-scale-x:\">AO 43 B2" }
    n387 --> n221@{ label: "<span style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Unimalleolar fracture posterior malleolus</span><br style=\"--tw-scale-x:\">AO Unclassifiable<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Lauge-Hansen PA</span><span style=\"--tw-scale-x:\"><br></span>" }
    n388 --> n389["Yes"] & n390["No"]
    n389 --> n391["Is there articular depression?"]
    n391 --> n392["Yes"] & n393["No"]
    n392 --> n394@{ label: "Distal tibia fracture<br style=\"--tw-scale-x:\">AO 43 B2" }
    n393 --> n395@{ label: "Distal tibia fracture<br style=\"--tw-scale-x:\">AO 43 B1" }
    n390 --> n15
    n396 --> n39
    n397 --> n40
    n398 --> n276@{ label: "Bimalleolar fracture (Medial + Posterior)<br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\">Bartonicek 4" }
    n271 --> n275@{ label: "Bimalleolar fracture (Medial + Posterior)<br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\">Bartonicek 3" }
    n270 --> n274@{ label: "Bimalleolar fracture (Medial + Posterior)<br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\">Lauge-Hansen PA<br style=\"--tw-scale-x:\">Bartonicek 2" }
    n269 --> n273@{ label: "Bimalleolar fracture (Medial + Posterior)<br style=\"--tw-scale-x:\">AO 44 B3<br style=\"--tw-scale-x:\">Lauge-Hansen PA<br>Bartonicek 1" }
    n268 --> n399@{ label: "Bimalleolar fracture (Medial + Posterior)<br style=\"--tw-scale-x:\">AO 44 A3<br style=\"--tw-scale-x:\">Lauge-Hansen Unclassifiable<br style=\"--tw-scale-x:\"><br>" }
    n400 --> n401["No"] & n402["Yes"]
    n401 --> n403@{ label: "Bimalleolar fracture (Lateral + Posterior)<br style=\"--tw-scale-x:\">AO unclassifiable<br style=\"--tw-scale-x:\">Lauge-Hansen unclassifiable<br style=\"--tw-scale-x:\">Weber A" }
    n402 --> n404["Is the posterior fragment posteromedial?"]
    n404 --> n405["No"] & n406["Yes"]
    n405 --> n407["Posterior extraincisural fragment"] & n408["Posterolateral fragment"] & n409["Posteromedial and posterolateral fragment"] & n410["Large posterolateral triangular fragment"]
    n407 --> n411@{ label: "Bimalleolar fracture (Lateral + Posterior)<br style=\"--tw-scale-x:\">AO unclassifiable<br style=\"--tw-scale-x:\">Lauge-Hansen unclassifiable<br style=\"--tw-scale-x:\">Weber A<br>Bartonicek 1" }
    n408 --> n412@{ label: "Bimalleolar fracture (Lateral + Posterior)<br style=\"--tw-scale-x:\">AO unclassifiable<br style=\"--tw-scale-x:\">Lauge-Hansen unclassifiable<br style=\"--tw-scale-x:\">Weber A<br style=\"--tw-scale-x:\">Bartonicek 2" }
    n409 --> n413@{ label: "Bimalleolar fracture (Lateral + Posterior)<br style=\"--tw-scale-x:\">AO unclassifiable<br style=\"--tw-scale-x:\">Lauge-Hansen unclassifiable<br style=\"--tw-scale-x:\">Weber A<br style=\"--tw-scale-x:\">Bartonicek 3" }
    n410 --> n414@{ label: "Bimalleolar fracture (Lateral + Posterior)<br style=\"--tw-scale-x:\">AO unclassifiable<br style=\"--tw-scale-x:\">Lauge-Hansen unclassifiable<br style=\"--tw-scale-x:\">Weber A<br style=\"--tw-scale-x:\">Bartonicek 4" }
    n406 --> n415@{ label: "Bimalleolar fracture (Lateral + Posterior)<br style=\"--tw-scale-x:\">AO 44 A3<br style=\"--tw-scale-x:\">Lauge-Hansen unclassifiable<br style=\"--tw-scale-x:\">Weber A" }
    n416 --> n230
    n417 --> n233
    n418 --> n241
    n419 --> n245
    n420 --> n126
    n421 --> n127

    n379@{ shape: diam}
    n6@{ shape: diam}
    n7@{ shape: rect}
    n8@{ shape: rect}
    n9@{ shape: rect}
    n10@{ shape: rect}
    n11@{ shape: cyl}
    n12@{ shape: cyl}
    n13@{ shape: cyl}
    n14@{ shape: cyl}
    n388@{ shape: diam}
    n15@{ shape: diam}
    n18@{ shape: cyl}
    n19@{ shape: cyl}
    n20@{ shape: diam}
    n21@{ shape: rect}
    n22@{ shape: rect}
    n23@{ shape: rect}
    n27@{ shape: cyl}
    n29@{ shape: diam}
    n32@{ shape: cyl}
    n33@{ shape: cyl}
    n34@{ shape: diam}
    n35@{ shape: rect}
    n36@{ shape: rect}
    n37@{ shape: rect}
    n286@{ shape: diam}
    n290@{ shape: diam}
    n41@{ shape: cyl}
    n264@{ shape: diam}
    n43@{ shape: diam}
    n400@{ shape: diam}
    n48@{ shape: diam}
    n49@{ shape: diam}
    n67@{ shape: diam}
    n68@{ shape: rect}
    n69@{ shape: rect}
    n70@{ shape: rect}
    n71@{ shape: rect}
    n72@{ shape: cyl}
    n73@{ shape: cyl}
    n74@{ shape: cyl}
    n75@{ shape: cyl}
    n76@{ shape: diam}
    n77@{ shape: rect}
    n78@{ shape: rect}
    n79@{ shape: rect}
    n80@{ shape: rect}
    n81@{ shape: cyl}
    n82@{ shape: cyl}
    n83@{ shape: cyl}
    n84@{ shape: cyl}
    n223@{ shape: diam}
    n227@{ shape: diam}
    n85@{ shape: diam}
    n86@{ shape: rect}
    n87@{ shape: rect}
    n88@{ shape: rect}
    n89@{ shape: rect}
    n90@{ shape: cyl}
    n91@{ shape: cyl}
    n92@{ shape: cyl}
    n93@{ shape: cyl}
    n94@{ shape: diam}
    n95@{ shape: rect}
    n96@{ shape: rect}
    n97@{ shape: rect}
    n98@{ shape: rect}
    n99@{ shape: cyl}
    n100@{ shape: cyl}
    n101@{ shape: cyl}
    n102@{ shape: cyl}
    n103@{ shape: diam}
    n104@{ shape: rect}
    n105@{ shape: rect}
    n106@{ shape: rect}
    n107@{ shape: rect}
    n108@{ shape: cyl}
    n109@{ shape: cyl}
    n110@{ shape: cyl}
    n111@{ shape: cyl}
    n307@{ shape: rect}
    n310@{ shape: diam}
    n112@{ shape: diam}
    n115@{ shape: diam}
    n118@{ shape: cyl}
    n119@{ shape: diam}
    n122@{ shape: diam}
    n336@{ shape: diam}
    n340@{ shape: diam}
    n128@{ shape: cyl}
    n129@{ shape: diam}
    n133@{ shape: diam}
    n136@{ shape: cyl}
    n138@{ shape: cyl}
    n139@{ shape: cyl}
    n140@{ shape: cyl}
    n141@{ shape: diam}
    n152@{ shape: rect}
    n145@{ shape: diam}
    n146@{ shape: rect}
    n147@{ shape: rect}
    n148@{ shape: rect}
    n345@{ shape: diam}
    n363@{ shape: diam}
    n249@{ shape: diam}
    n153@{ shape: diam}
    n154@{ shape: rect}
    n155@{ shape: rect}
    n156@{ shape: rect}
    n157@{ shape: diam}
    n158@{ shape: rect}
    n159@{ shape: rect}
    n160@{ shape: cyl}
    n253@{ shape: diam}
    n260@{ shape: diam}
    n164@{ shape: diam}
    n169@{ shape: cyl}
    n170@{ shape: cyl}
    n171@{ shape: cyl}
    n172@{ shape: cyl}
    n173@{ shape: diam}
    n178@{ shape: cyl}
    n179@{ shape: cyl}
    n180@{ shape: cyl}
    n181@{ shape: cyl}
    n182@{ shape: diam}
    n187@{ shape: cyl}
    n188@{ shape: cyl}
    n189@{ shape: cyl}
    n190@{ shape: cyl}
    n191@{ shape: diam}
    n196@{ shape: cyl}
    n197@{ shape: cyl}
    n198@{ shape: cyl}
    n199@{ shape: cyl}
    n201@{ shape: diam}
    n214@{ shape: cyl}
    n215@{ shape: cyl}
    n216@{ shape: cyl}
    n217@{ shape: cyl}
    n218@{ shape: diam}
    n387@{ shape: rect}
    n226@{ shape: cyl}
    n344@{ shape: rect}
    n285@{ shape: rect}
    n233@{ shape: diam}
    n236@{ shape: cyl}
    n240@{ shape: cyl}
    n241@{ shape: diam}
    n244@{ shape: cyl}
    n245@{ shape: diam}
    n248@{ shape: cyl}
    n252@{ shape: cyl}
    n255@{ shape: cyl}
    n263@{ shape: cyl}
    n265@{ shape: rect}
    n266@{ shape: rect}
    n267@{ shape: diam}
    n268@{ shape: rect}
    n269@{ shape: rect}
    n270@{ shape: rect}
    n271@{ shape: rect}
    n398@{ shape: rect}
    n272@{ shape: cyl}
    n232@{ shape: cyl}
    n287@{ shape: rect}
    n288@{ shape: rect}
    n396@{ shape: rect}
    n39@{ shape: cyl}
    n289@{ shape: cyl}
    n291@{ shape: rect}
    n292@{ shape: rect}
    n397@{ shape: rect}
    n40@{ shape: cyl}
    n293@{ shape: cyl}
    n294@{ shape: diam}
    n295@{ shape: rect}
    n296@{ shape: rect}
    n297@{ shape: rect}
    n298@{ shape: rect}
    n299@{ shape: cyl}
    n300@{ shape: cyl}
    n301@{ shape: cyl}
    n302@{ shape: cyl}
    n303@{ shape: rect}
    n304@{ shape: rect}
    n305@{ shape: rect}
    n306@{ shape: cyl}
    n309@{ shape: rect}
    n416@{ shape: rect}
    n311@{ shape: rect}
    n312@{ shape: rect}
    n417@{ shape: rect}
    n313@{ shape: diam}
    n314@{ shape: rect}
    n315@{ shape: rect}
    n316@{ shape: cyl}
    n325@{ shape: diam}
    n326@{ shape: rect}
    n329@{ shape: rect}
    n330@{ shape: rect}
    n331@{ shape: rect}
    n332@{ shape: cyl}
    n333@{ shape: cyl}
    n334@{ shape: cyl}
    n335@{ shape: cyl}
    n337@{ shape: rect}
    n338@{ shape: rect}
    n420@{ shape: rect}
    n126@{ shape: cyl}
    n339@{ shape: cyl}
    n341@{ shape: rect}
    n342@{ shape: rect}
    n421@{ shape: rect}
    n127@{ shape: cyl}
    n343@{ shape: cyl}
    n229@{ shape: cyl}
    n346@{ shape: rect}
    n347@{ shape: rect}
    n418@{ shape: rect}
    n348@{ shape: diam}
    n349@{ shape: rect}
    n350@{ shape: rect}
    n351@{ shape: diam}
    n352@{ shape: cyl}
    n353@{ shape: rect}
    n354@{ shape: rect}
    n355@{ shape: rect}
    n356@{ shape: rect}
    n357@{ shape: cyl}
    n358@{ shape: cyl}
    n359@{ shape: cyl}
    n362@{ shape: cyl}
    n364@{ shape: rect}
    n365@{ shape: rect}
    n419@{ shape: rect}
    n366@{ shape: diam}
    n367@{ shape: rect}
    n368@{ shape: rect}
    n369@{ shape: cyl}
    n370@{ shape: diam}
    n371@{ shape: rect}
    n372@{ shape: rect}
    n373@{ shape: rect}
    n374@{ shape: rect}
    n375@{ shape: cyl}
    n376@{ shape: cyl}
    n377@{ shape: cyl}
    n378@{ shape: cyl}
    n382@{ shape: diam}
    n383@{ shape: rect}
    n384@{ shape: rect}
    n385@{ shape: cyl}
    n386@{ shape: cyl}
    n221@{ shape: cyl}
    n389@{ shape: rect}
    n390@{ shape: rect}
    n391@{ shape: diam}
    n392@{ shape: rect}
    n393@{ shape: rect}
    n394@{ shape: cyl}
    n395@{ shape: cyl}
    n276@{ shape: cyl}
    n275@{ shape: cyl}
    n274@{ shape: cyl}
    n273@{ shape: cyl}
    n399@{ shape: cyl}
    n401@{ shape: rect}
    n402@{ shape: rect}
    n403@{ shape: cyl}
    n404@{ shape: diam}
    n405@{ shape: rect}
    n406@{ shape: rect}
    n411@{ shape: cyl}
    n412@{ shape: cyl}
    n413@{ shape: cyl}
    n414@{ shape: cyl}
    n415@{ shape: cyl}
